//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Blood_Bank_Entities : DbContext
    {
        public Blood_Bank_Entities()
            : base("name=Blood_Bank_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Announcement> Announcement { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Contact> Contact { get; set; }
        public DbSet<Content> Content { get; set; }
        public DbSet<ContentType> ContentType { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<District> District { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<SystemUser> SystemUser { get; set; }
        public DbSet<MentionTwitter> MentionTwitter { get; set; }
        public DbSet<MessageLog> MessageLog { get; set; }
    }
}
