//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentionTwitter
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public int UsedCount { get; set; }
        public bool Valid { get; set; }
    }
}
