//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public int Id { get; set; }
        public string ReferenceNo { get; set; }
        public string MessageText { get; set; }
        public string UsedAmount { get; set; }
        public string Type { get; set; }
        public string Credits { get; set; }
        public string Phone { get; set; }
    }
}
