//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public int AnnouncementId { get; set; }
        public string ContactIds { get; set; }
        public string MessageText { get; set; }
        public string AuthUser { get; set; }
        public string Channel { get; set; }
        public bool Active { get; set; }
        public bool Approve { get; set; }
        public bool Send { get; set; }
    
        public virtual Announcement Announcement { get; set; }
    }
}
